title: "John Juszczak"

author:
  name: "John Juszczak"
  bio: "Software Engineer"
  location: "Los Angeles"
  links:
    - label: "Website"
      url: "https://johnjuszczak.github.io"
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/john-juszczak-434408ab/"
    - label: "GitHub"
      url: "https://github.com/johnjuszczak"

url: https://johnjuszczak.github.io
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.27.3"
minimal_mistakes_skin: dark

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-feed

collections:
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  - scope: { path: "", type: projects }
    values:
      layout: single

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-ZE022WGL44"
