name: Build & Deploy
on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.6'
          bundler-cache: true

      - name: Build
        env:
          JEKYLL_ENV: production
        run: bundle exec jekyll build -d ${{ vars.BUILD_DIR }}

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: ${{ vars.PAGES_BRANCH }}
          folder: ${{ vars.BUILD_DIR }}
          force: false
          clean: true
          clean-exclude: |
            pr-preview/
            .nojekyll
