name: PR Previews
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.6'
          bundler-cache: true

      - name: Build
        if: github.event.action != 'closed'
        env:
          JEKYLL_ENV: development
        run: bundle exec jekyll build -d ${{ vars.BUILD_DIR }} --baseurl "/pr-preview/pr-${{ github.event.number }}"

      - name: Auto Action Preview
        id: preview-action
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ${{ vars.BUILD_DIR }}
          preview-branch: ${{ vars.PAGES_BRANCH }}
          action: auto
          comment: true

      - name: Output preview URL in action log
        if: steps.preview-action.outputs.deployment-action == 'deploy'
        run: echo "Preview visible at ${{ steps.preview-action.outputs.preview-url }}"
